services:
  - type: web
    name: yt-downloader-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    branch: main
    autoDeploy: true
